#
# Publica la imagen Docker de Outer.one CE (solo AMD64)
# Se ejecuta en pushes a develop, master o cuando se crean tags.
#

name: Publish MEGA CE docker images for AMD64

on:
  push:
    branches:
      - develop
      - master
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    env:
      GIT_REF: ${{ github.head_ref || github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1

      - name: Set Docker tag
        run: |
          TAG_NAME=${GIT_REF}
          if [ "${{ github.ref_name }}" = "master" ]; then
            TAG_NAME=latest
          fi
          echo "DOCKER_TAG=sendingtk/chatwoot:${TAG_NAME}" >> $GITHUB_ENV

      - name: Log in to DockerHub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push AMD64 image
        uses: docker/build-push-action@v6.5.0
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ env.DOCKER_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
